# Copyright (c) 2022 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

site_name: "ExeKGLib"
site_author: "Mohamed Gad-Elrab"
site_description: "Library for executable ML pipelines represented by KGs."
site_url: "https://boschresearch.github.io/ExeKGLib"

repo_name: "boschresearch/ExeKGLib"
repo_url: "https://github.com/boschresearch/ExeKGLib"
edit_uri: "edit/main/docs"

site_dir: .site

nav:
  - Overview:
    - Overview: index.md
    - Ready-to-use ML-related tasks and methods: supported-methods.md
    - Usage: usage.md
    - Installation: installation.md
    - Extending: extending.md
    - External resources: external-resources.md
  - Code Reference: reference/
  - Development:
    - Adding a new ML-related task and method: adding-new-task-and-method.md
    - Documentation of exe_kg_lib.classes.tasks package: tasks-package-documentation.md
    - Contributing: contributing.md
#    - Coverage: exported/coverage/report.html
#    - Tests: exported/tests/report.html
  - License: license.md

theme:
  name: material
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  font: false # Disabled because of GDPR, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#autoloading
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - scheme: slate
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - gen-files:
#      'exclude' throws a "Config value" warnings, as it is a custom property
      exclude:
        - "/examples"
        - "__init__"
      scripts:
        - docs/generate-code-reference.py
  - git-revision-date-localized:
      fallback_to_build_date: true
  - literate-nav:
      nav_file: code-nav.md
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - search

extra:
  generator: false
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # Sortable tables (see https://squidfunk.github.io/mkdocs-material/reference/data-tables)
  - https://unpkg.com/tablesort/dist/tablesort.min.js
  - js/tablesort.js

  # MathJax (see https://squidfunk.github.io/mkdocs-material/reference/mathjax)
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
